### PR TITLE
Drop py27

### PR DESCRIPTION
**Pull request by dwhswenson**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

[attrs 22.1.0 dropped Python 2.7 support](https://github.com/python-attrs/attrs/releases/tag/22.1.0). This causes pytest runs on 2.7 to exit with an error. See https://github.com/conda-forge/pytest-feedstock/issues/148

I think there's also something that needs to be done in somewhere to mark build 0 as broken? Can't immediately remember details on how that's done; will be happy to address it tomorrow.

### CODE REVIEW

**Comment by dwhswenson** [comment]
@conda-forge-admin, please rerender

**Comment by nicoddemus** [comment]
> I think there's also something that needs to be done in somewhere to mark build 0 as broken? Can't immediately remember details on how that's done; will be happy to address it tomorrow.

Indeed: https://conda-forge.org/docs/maintainer/updating_pkgs.html#removing-broken-packages

**Review by nicoddemus — CHANGES_REQUESTED** [review]

**Comment by dwhswenson** [comment]
@nicoddemus : Done and done -- changes made here; and PR open on admin-requests.

Please let me know if there's anything else I can do to help with this! Thanks!

**Review by nicoddemus — APPROVED** [review]
Thanks @dwhswenson!

**Pull request merged**
